// <auto-generated />
namespace MVC_CodeAlong_110518_Amer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class moreValidation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moreValidation));
        
        string IMigrationMetadata.Id
        {
            get { return "201805111303432_moreValidation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
